// <auto-generated />
namespace MVC_Kutuphane_Otomasyonu.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddGuncellenmeTarihiTo_Kitaplar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddGuncellenmeTarihiTo_Kitaplar));
        
        string IMigrationMetadata.Id
        {
            get { return "202511011055071_AddGuncellenmeTarihiTo_Kitaplar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
