// <auto-generated />
namespace MVC_Kutuphane_Otomasyonu.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Fix_UyeIdType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fix_UyeIdType));
        
        string IMigrationMetadata.Id
        {
            get { return "202510281051134_Fix_UyeIdType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
